project:
  type: book
  output-dir: _book

documentclass: book

github-repo: oulib-resdata/metrics

book:
  title: "Research Workshop Attendance, Marketing, and Satisfaction"
  author: "C.M. Curry (STEM Services) and B. Narr (Metrics Coordinator)"
  search: true
  downloads: [pdf]
  date: last-modified
  page-navigation: true

  chapters:
    - index.qmd
    - part: overall_analysis.qmd
      chapters:
        - descriptive_numbers.qmd
        - marketing.qmd
        - attendance.qmd
        - satisfaction.qmd
    - part: topic_details.qmd
      chapters:
        - topics.qmd
        - VIZ101.qmd
#   - references.qmd
    - technical_background.qmd
#  appendices:
#    - something.qmd

comments:
  hypothesis: true


bibliography:
  - references.bib
  - packages.bib


format:
  html:
    toc: false
    code-background: true
    code-copy: true
    css: style.css
    fontsize: 12pt
    reference-location: margin
    citation-location: margin
  pdf:
    documentclass: book
    keep-tex: false
    cite-method: natbib
    reference-location: margin
    citation-location: margin
# reference_docx: word_styles.docx